// Cart constants
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';

// Products constants
export const ADD_PRODUCT_TO_PRODUCTS = 'ADD_PRODUCT_TO_PRODUCTS';
export const DELETE_PRODUCT_FROM_PRODUCTS = 'DELETE_PRODUCT_FROM_PRODUCTS';
export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY';
export const ADD_PRODUCT_TO_PRODUCTS_REPLACED =
  'ADD_PRODUCT_TO_PRODUCTS_REPLACED';
export const ADD_PRODUCT_FROM_API = 'ADD_PRODUCT_FROM_API';
